import type { AssistantCopy } from "@/components/AssistantChat";

/**
 * Copy for the parts of the site that wrap every page — top bar, navigation,
 * footer, mobile contact bar and the assistant.
 *
 * It lives here rather than inside the homepage because a visitor arriving from
 * search on a city page needs the same header, footer and contact actions. Landing
 * without them is landing on a dead end.
 */

export type ChromeCopy = {
  topbar: { service: string; spanish: string; license: string };
  nav: {
    work: string;
    services: string;
    builders: string;
    process: string;
    about: string;
    estimate: string;
    menu: string;
    home: string;
  };
  footer: {
    body: string;
    contact: string;
    links: string;
    areas: string;
    location: string;
    rights: string;
    ownership: string;
    profile: string;
    privacy: string;
  };
  mobile: { call: string; text: string; quote: string };
  chat: AssistantCopy;
};

const chatEn: AssistantCopy = {
  label: "Business assistant",
  title: "Ask Perez",
  status: "Online",
  trigger: "Ask us",
  intro:
    "Ask about framing services, our service area, estimates, or how to prepare your project. For anything the assistant can't confirm, call or text us.",
  chips: ["Do you serve my city?", "What plans should I send?", "Can I request an estimate?"],
  placeholder: "Type your question…",
  send: "Send message",
  close: "Close business assistant",
  open: "Open business assistant",
  error:
    "We couldn't get an answer just now. Please try again, or call us and we'll help you directly.",
  busy: "That's a lot of messages at once. Give it a moment and try again.",
  unavailable:
    "The assistant isn't available right now. Call or text us and we'll help you directly.",
  offline: "Call or text",
  disclaimer:
    "Answers are generated by our assistant. Scope, pricing, and schedule are confirmed by our team.",
  callAction: "Call us",
  textAction: "Text us",
  powered: "Leadprime",
};

const chatEs: AssistantCopy = {
  label: "Asistente del negocio",
  title: "Pregunta a Perez",
  status: "En línea",
  trigger: "Pregúntanos",
  intro:
    "Pregunta sobre servicios de framing, área de cobertura, estimados o cómo preparar tu proyecto. Si el asistente no puede confirmar algo, llámanos o mándanos un texto.",
  chips: ["¿Trabajan en mi ciudad?", "¿Qué planos debo enviar?", "¿Puedo pedir un estimado?"],
  placeholder: "Escribe tu pregunta…",
  send: "Enviar mensaje",
  close: "Cerrar asistente del negocio",
  open: "Abrir asistente del negocio",
  error:
    "No pudimos obtener una respuesta en este momento. Intenta de nuevo o llámanos y te ayudamos directamente.",
  busy: "Son muchos mensajes seguidos. Espera un momento e intenta de nuevo.",
  unavailable:
    "El asistente no está disponible en este momento. Llámanos o mándanos un texto y te atendemos directo.",
  offline: "Llámanos o escríbenos",
  disclaimer:
    "Las respuestas las genera nuestro asistente. El alcance, precio y calendario los confirma nuestro equipo.",
  callAction: "Llamar",
  textAction: "Mandar texto",
  powered: "Leadprime",
};

export const chrome: Record<"en" | "es", ChromeCopy> = {
  en: {
    topbar: {
      service: "Serving San Pablo + 35 miles",
      spanish: "Se habla español",
      license: "CSLB #1144949",
    },
    nav: {
      work: "Our Work",
      services: "Services",
      builders: "For Builders",
      process: "Process",
      about: "About",
      estimate: "Free Estimate",
      menu: "Open navigation",
      home: "Home",
    },
    footer: {
      body: "Structural expertise for framing, additions, and renovations throughout the Bay Area.",
      contact: "Contact",
      links: "Explore",
      areas: "Service areas",
      location: "San Pablo, CA 94806",
      rights: "All rights reserved.",
      ownership: "A business-owned website.",
      profile: "Business profile",
      privacy: "Privacy",
    },
    mobile: { call: "Call", text: "Text", quote: "Free Estimate" },
    chat: chatEn,
  },
  es: {
    topbar: {
      service: "San Pablo y 35 millas alrededor",
      spanish: "Hablamos español",
      license: "CSLB #1144949",
    },
    nav: {
      work: "Proyectos",
      services: "Servicios",
      builders: "Para builders",
      process: "Proceso",
      about: "Nosotros",
      estimate: "Estimado gratis",
      menu: "Abrir navegación",
      home: "Inicio",
    },
    footer: {
      body: "Experiencia estructural para framing, ampliaciones y renovaciones en el Área de la Bahía.",
      contact: "Contacto",
      links: "Explora",
      areas: "Zonas de servicio",
      location: "San Pablo, CA 94806",
      rights: "Todos los derechos reservados.",
      ownership: "Un sitio propiedad del negocio.",
      profile: "Perfil del negocio",
      privacy: "Privacidad",
    },
    mobile: { call: "Llamar", text: "Texto", quote: "Estimado gratis" },
    chat: chatEs,
  },
};
